### ISSUE TITLE
PyPI sdist

### ISSUE THREAD

**Issue by jayvdb** [open-contracting/ocdskit#105]
Like https://github.com/open-contracting/ocds-merge/issues/23 , the PyPI sdist here is missing the LICENSE and test data.

**Comment by jpmckinney** [comment]
Thanks, @jayvdb! I added MANIFEST.in to HEAD. I have some other changes I want to schedule into the next release. Let me know if you need a release more urgently.

**Comment by jayvdb** [comment]
Not urgent.  I need to finish packaging of ocdsmerge first anyway.
