### ISSUE TITLE
package-releases, package-records: add dummy values option

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/ocdskit#111]
A common use for the `package-releases` command is to wrap a release shared by a publisher in a release package so it can be tested using the Data Review Tool and the results shared with the publisher.

It would be useful if there was a 'dummy-values' option to populate the fields in the package metadata with valid data, so that CoVE only reports the actual issues with the release, rather than issues with the package metadata introduced by using package-releases

The fields can be populated using the existing parameters but this is time consuming.

A similar option could be added to package-records

**Comment by jpmckinney** [comment]
Done in af6631fc7563760fffa7fc0529cf22d04b3172e4. Released in 0.1.4.
