### ISSUE TITLE
OC4IDS transforms: Handling multiple contracting processes

### ISSUE THREAD

**Issue by kindly** [open-contracting/ocdskit#130]
There are a few areas in the OCDS -> OC4IDS conversion where what to do with data across different contracting processes is not currently clearly defined.  I do not think there is a perfect solution to these but below outlines what the current implementation does so that we can discuss other potential solutions.

#### planning/project/title, project/planning/description (planning and budget extension)

If there are any contradictions i.e one contract says the title is different from another a warning is raised and the field is ignored in that case.  If all contracting processes agree (when the fields exists in them) then the value is still used.

####  tender/title, tender/description, /planning/rationale

If there a multiple contradicting process then we concatenate the strings and put the ocid
in angle brackets like
```
<someocid> a tender description
<anotherocid> another description
```
If there is only one contracting processes then the ocid part is omitted.

####  parties

We need to deal with `party/id` from different contracting processes conflicting and also if there are parties in multiple contracting processes that are the same, we should treat them as the same party.

Current logic:
- If all parties/id are unique across contracting processes then do nothing and add all parties to the project.
- If there are conflicting parties/id then look at the `identifier` field and if there are `scheme` and `id` make an id of `somescheme-someid` and use that in order to match parties across processes.  If there are different roles then add them to the same party.  Use the other fields from the first party found with this id.
- If there is no `identifier` then make up a new auto increment number and use that as the `id`. 
- If there is no `identifer` and all fields apart from `roles` and `id` are the same across parties then treat that as a single party and add the roles together and use a single generated `id`

####  docs

If there are are only unique project/documents/id keep the ids the same. Otherwise create a new auto-increment for all docs.

**Comment by duncandewhurst** [comment]
For `planning/project/sector` - since this is an array, I would prefer to add the sectors from all contracting processes.

Otherwise all sounds good.

**Comment by kindly** [comment]
Sector now gets unique  scheme-id strings from all contracting processes.

**Comment by jpmckinney** [comment]
The solutions seems reasonable to me. @duncandewhurst If you agree, then I think this issue can be closed?

**Comment by duncandewhurst** [comment]
All good!
