### ISSUE TITLE
Packages fail validation - no "version" key and "publishedDate" key given as "published_date"

### ISSUE THREAD

**Issue by pindec** [open-contracting/ocdskit#140]
While using convert-to-oc4ids on the command line with --all-transforms and --package options set, I noticed that the resulting project package data fails validation.

This seems like an issue in the base packager.

Looks like the published date key is incorrect [in base.py parse_package_arguments](https://github.com/open-contracting/ocdskit/blob/master/ocdskit/cli/commands/base.py#L142) (should be "publishedDate").

Can we also have an argument in [add_package_arguments](https://github.com/open-contracting/ocdskit/blob/master/ocdskit/cli/commands/base.py#L115) to add "version"?

**Comment by jpmckinney** [comment]
The issue is specific to `convert-to-oc4ids` (other commands output `publishedDate` correctly). I'll have a look.

**Comment by jpmckinney** [comment]
Fixed. I'll make a new release shortly. `version` is now automatically set to 0.9 for OC4IDs, but this can be overridden with `--version`.

**Comment by jpmckinney** [comment]
0.2.7 is released. Thanks for reporting!
