### ISSUE TITLE
convert-to-oc4ids: empty fields

### ISSUE THREAD

**Issue by yolile** [open-contracting/ocdskit#144]
I converted https://raw.githubusercontent.com/open-contracting/sample-data/master/fictional-example/1.1/ocds-213czf-000-00001-02-tender.json to a oc4ids project with the convert-to-oc4ids command, and got: 

```json

{
  "contractingProcesses":[...],
  "sector":[""],
  "documents":[]
}
```

with the fields `sector` and `documents` empty, shouldn't it instead just avoid these empty fields?

cc @antonioherrera

**Comment by jpmckinney** [comment]
I've added it to the project board: should be fairly straightforward to fix and test.
