### ISSUE TITLE
indent: Encoding issue on Windows

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/ocdskit#148]
Running the following commands on Linux results an utf-8 encoded file:

```
curl http://200.13.162.79/datosabiertos/HC1/HC1_datos_2020_json.zip > honduras.zip
unzip -o honduras.zip
ocdskit indent HC1_datos_2020.json
```

But running the equivalent commands on Windows results in an iso-8859-1 encoded file:

```
curl http://200.13.162.79/datosabiertos/HC1/HC1_datos_2020_json.zip > honduras.zip
tar -x -f honduras.zip
ocdskit indent HC1_datos_2020.json
```

On Windows, the output of `more HC1_datos_2020.json` differs before and after running `ocdskit indent`:

Before indenting, the output includes:

```json
"name": "Secretaria de Salud P\u00fablica"
```

After indenting, the output includes:

```json
"name": "Secretaria de Salud P�blica"
```

`PYTHONIOENCODING` is set to `utf-8` and the terminal code page is set to `65001` (utf-8).

**Comment by jpmckinney** [comment]
What precise version of Windows are you running? Apparently some things were fixed in Windows 10 October 2018 Update (build 1809).

How did you set the terminal code page? `chcp 65001`? Did you set `LC_CTYPE=en_US.utf-8`? What is the output of `python -c "import sys; print(sys.stdout.encoding)"`?

**Comment by duncandewhurst** [comment]
> What precise version of Windows are you running? Apparently some things were fixed in Windows 10 October 2018 Update (build 1809).

Windows 10 Pro version 1909 OS build 18363.900

> How did you set the terminal code page?

 `chcp 65001`

> Did you set `LC_CTYPE=en_US.utf-8`? 

No. I tested again after setting it and got the same result.

> What is the output of `python -c "import sys; print(sys.stdout.encoding)"`?

utf-8 (before and after setting LC_CTYPE)

**Comment by jpmckinney** [comment]
> After indenting, the output includes:

How are you reading the output? Can you upload it?

**Comment by duncandewhurst** [comment]
For troubleshooting purposes, I am reading the output using `more`, but originally I came across the issue because I tried to run `cat HC1_datos_2020.json | ocdskit compile > honduras_compiled_releases.json` after following the steps in [this section](https://colab.research.google.com/drive/12ieZz3cx-bVGBoX4pOUpqYaA-B9al6Y8#scrollTo=SRefUu2zvT6P) of the OCDS Kit Learning Lab to download, extract and indent the file. `ocdskit compile` reported an encoding error and suggested trying `--encoding iso-8859-1`.

I've uploaded the file [before indenting](https://drive.google.com/file/d/1WaVc6aoFWMQdS5m95yr8WTWf773T3ymo/view?usp=sharing) and [after indenting](https://drive.google.com/file/d/1Vdm-_oQpEVV-Mmw9mAAyjT40N7HnojRs/view?usp=sharing).

**Comment by jpmckinney** [comment]
Hmm, okay, I'll need to check how Windows determines the output encoding for the indent command. The behavior is a bit surprising.

**Comment by jpmckinney** [comment]
@duncandewhurst Can you use `ocdskit --ascii indent` and re-upload the output?

**Comment by duncandewhurst** [comment]
Thanks for continuing to troubleshoot! Let me know if a screen-share would be helpful:

https://drive.google.com/file/d/1C9sTWf-4cv6auXJu5M-10YIl3s4zrb83/view?usp=sharing

**Comment by jpmckinney** [comment]
I notice the latest document is identical to an earlier one, which is because the indent command ignores the `--ascii` option 🙃 I'll fix that first.

**Comment by jpmckinney** [comment]
@duncandewhurst I've now fixed that on HEAD, if you can install from GitHub and run again.

**Comment by duncandewhurst** [comment]
I've uploaded the new version to the same URL: https://drive.google.com/file/d/1C9sTWf-4cv6auXJu5M-10YIl3s4zrb83/view?usp=sharing

**Comment by jpmckinney** [comment]
Fascinating. The ASCII output correctly encodes the UTF-8 character (e.g. `\u00f3` for `ó`).

Anyway, looks like there's another magic environment variable to make Windows use UTF8 like the rest of the world: `PYTHONUTF8=1`

https://dev.to/methane/python-use-utf-8-mode-on-windows-212i

**Comment by jpmckinney** [comment]
Also, should have asked earlier, what version of Python is this? `python --version`

**Comment by duncandewhurst** [comment]
> Anyway, looks like there's another magic environment variable to make Windows use UTF8 when reading/writing files like the rest of the world: `PYTHONUTF8=1`

Ah, that did the trick. I've added it to the learning lab instructions for Windows users.

Python version is 3.8.4

**Comment by jpmckinney** [comment]
I've added that instruction to the docs. Closing.
