### ISSUE TITLE
mapping-sheet: extension column is blank for Milestone Documents extension

### ISSUE THREAD

**Issue by romifz** [open-contracting/ocdskit#156]
Example:

```bash
$ ocdskit mapping-sheet release-schema.json --extension https://raw.githubusercontent.com/open-contracting-extensions/ocds_milestone_documents_extension/master/extension.json --extension-field extension > mapping-sheet.csv
```

**Comment by jpmckinney** [comment]
That's a weird extension, because all it does is set `deprecated` to `null`. Personally, I think it's a bit weird that the extension exists; all it does it make it so that the Data Review Tool stops complaining about that deprecated field.

Since the field is defined by OCDS, I think it makes sense for the extension column to be blank.

**Comment by romifz** [comment]
I see. That makes sense, although it makes things confusing for me as well.

Milestone documents is a core extension, so it is included in the OCDS mapping template. Extension fields are pushed to the end of the sheet, and each group is preceded by the name and description of the extension that adds the field.

With the current update, I have no way to identify which fields have been modified by the Milestone documents extension, and since they are not deprecated anymore, they appear in the main sections. Before the last `mapping-sheet` update I've been using a custom method to dereference the patched schema and copy the extension name down the schema tree for sections added by extensions using refs, but due to recent changes in the ProfileBuilder ([this commit](https://github.com/open-contracting/extension_registry.py/commit/d8833f39ca490cee926a81ed92fb77264453ee26) I think, but I'm not really sure), I can't do this anymore. Before the change, the extension field appeared in the top sections altered by Milestone documents, like `tender/milestones/documents`.

I know that this may not be an issue of ocdskit anymore, but I don't know what to do with Milestone documents, maybe we shouldn't be applying this extension at all?

**Comment by jpmckinney** [comment]
I recommend acting like that extension doesn’t exist. Extensions shouldn’t be in-deprecating fields.

**Comment by romifz** [comment]
That makes sense, thanks!
