### ISSUE TITLE
convert-to-oc4ids: remove copy of 'finalAudit' documents from ocds to oc4ids

### ISSUE THREAD

**Issue by pindec** [open-contracting/ocdskit#165]
convert-to-oc4ids has a [final_audit method](https://github.com/open-contracting/ocdskit/blob/f0d09835f5b1e159c9662d8b706c5b3d0439cf47/ocdskit/oc4ids.py#L914) to copy documents tagged 'finalAudit' from ocds `contract.implementation.documents` to oc4ids `project.documents`, but OC4IDS issues [#268](https://github.com/open-contracting/infrastructure/issues/268) and [#269](https://github.com/open-contracting/infrastructure/issues/269) remove this code (replacing it with 'technicalAuditReport' and 'financialAuditReport') and updates mapping advice for project completion.

Since there is no easy way to disambiguate between the types of audit document from ocds data, we should consider removing this mapping from convert-to-oc4ids.

**Comment by duncandewhurst** [comment]
Since document type is an open codelist, I think it's OK to keep this mapping.

**Comment by jpmckinney** [comment]
Closing based on @duncandewhurst's comment, but can re-open as needed.
