### ISSUE TITLE
convert-to-oc4ids: transform copies additional fields (items, milestones) to contractingProcesses.summary.tender

### ISSUE THREAD

**Issue by pindec** [open-contracting/ocdskit#168]
Generated projects include `items` and `milestones` additional fields in the `contractingProcesses.summary.tender` object.

**Comment by duncandewhurst** [comment]
This is based on the second part of the mapping for project scope:

> Check `planning.documents` for documents with `.type` set to 'projectScope' or infer from `tender.items` or `tender.milestones`.

Although those fields aren't part of the OC4IDS schema, the idea was to make the `items` and `milestones` readily available to an analyst working with the output of `convert-to-oc4ids`.
