### ISSUE TITLE
mapping-sheet: Add codelist column to output

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/ocdskit#183]
In order to know which fields permit translated values, it would be useful if there was a column to indicate which fields use codelists.

Some fields use codelists but don't include a link to the codelist in the field description, e.g. `Observation.unit.scheme`.

**Comment by jpmckinney** [comment]
You can try `ocdskit mapping-sheet --codelist --infer-required my-schema.json` with `pip install -e git+https://github.com/open-contracting/ocdskit.git`

**Comment by jpmckinney** [comment]
Hold on - need to commit a fix.

**Comment by duncandewhurst** [comment]
Looks good! Thanks

**Comment by jpmckinney** [comment]
Cool, 1.0.4 is building and will be available shortly.
