### ISSUE TITLE
Migrate scripts from standard and public-private-partnerships

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/ocdskit#19]
For `standard`, see https://github.com/open-contracting/standard/issues/631

**Comment by Bjwebb** [comment]
For our OS4D work we discussed moving scripts, particularly translation scripts, into a generic repo. However we only use them for OCDS (standard & PPPs) at the moment, so moving all the scripts into ocdskit probably makes most sense for now.

**Comment by Bjwebb** [comment]
Moving scripts to ocdskit should mean we no longer need to have the OCDS standard repo as a requirements of the PPPs repo - https://github.com/open-contracting/public-private-partnerships/blob/master/requirements.txt#L35-L36

**Comment by jpmckinney** [comment]
@Bjwebb @robredpath Where in the timeline is moving scripts from the `standard` repo to this repo (or whatever consolidated repo)?

**Comment by robredpath** [comment]
@Bjwebb any sense of scale on this? Not sure how far down the dependency rabbit hole this will take us. Hours/days/weeks/months/years?

**Comment by Bjwebb** [comment]
This should be a matter of hours.

**Comment by jpmckinney** [comment]
What does OCDS for PPPs depend on from the standard repo?

**Comment by Bjwebb** [comment]
I think it's just these two babel extractors https://github.com/open-contracting/standard/blob/1.1-dev/setup.py#L9-L10

**Comment by jpmckinney** [comment]
ocdskit may not be the best home for those, but perhaps one of the OCP or ODS sphinx repos?

**Comment by jpmckinney** [comment]
Opened https://github.com/open-contracting/ocds_sphinx_directives/issues/7
