### ISSUE TITLE
Add link to Docker image to readme

### ISSUE THREAD

**Issue by mxcoder** [open-contracting/ocdskit#56]
I have been working with some Mexican OCDS stuff, and I decided to create this little piece:

https://hub.docker.com/r/ricardoe/ocdskit/

Let me know if this is problematic somehow. If its helpful I'm more than willing to collaborate.

**Comment by jpmckinney** [comment]
Awesome! We'd be happy to link to the Docker image from the installation instructions of the readme. Is that alright with you?

**Comment by mxcoder** [comment]
Sure thing, also let me know if you would prefer to take it over and publish it under OCDS org. But feel free to share it as is.
