### ISSUE TITLE
combine-release-packages

### ISSUE THREAD

**Issue by JArielMG** [open-contracting/ocdskit#62]
When generating the out.json file by combining the release-packages files, the file shows the accented words with symbols and all the text in a single line.

The command used to generate the file is:

curl <local_folder> | jq -crM. | ocdskit combine-record-packages> out.json

From these files, how is the file generated in XLSX format? 

@jpmckinney  Thank you

**Comment by jpmckinney** [comment]
Do you mean the kind of Excel file that the [validator](http://standard.open-contracting.org/validator/) offers?

**Comment by JArielMG** [comment]
No, when you combine the 193 json files and make a single file in json format, it shows the letters accented with symbols, for example:

- p\u00fablicas = públicas
- contrataci\u00f3n = contratación

and all the text is in a single line.

**Comment by jpmckinney** [comment]
If you are reading the JSON file as a human (instead of as a machine), I can see the benefit of encoding non-ASCII characters as UTF-8 instead of escaped sequences. I've opened #63 to fix that.

To make the text be indented and split across many lines, use `--pretty`
