### ISSUE TITLE
Links from pypi project page to 'using jq' and 'using the command line' seem to be broken

### ISSUE THREAD

**Issue by pindec** [open-contracting/ocdskit#72]
In https://pypi.org/project/ocdskit/, the links to _using jq_ and _using the command line_ give 404 not found errors.

They point to [/docs/Using_jq.md](https://pypi.org/docs/Using_jq.md) & [/docs/Using_the_command_line.md](https://pypi.org/docs/Using_the_command_line.md).

**Comment by jpmckinney** [comment]
This was fixed in https://github.com/open-contracting/ocdskit/pull/68, but there hasn't been a reason to make a release yet.
