### ISSUE TITLE
Pull out some of compile command into library functions

### ISSUE THREAD

**Issue by kindly** [open-contracting/ocdskit#79]
Some compile command functions, i.e making compiled releases and version releases, can be pulled out into separate functions

**Comment by kindly** [comment]
Relates to https://github.com/open-contracting/kingfisher/issues/268

**Comment by jpmckinney** [comment]
If we pull out behavior, it should at least include grouping releases by OCID – otherwise users should simply use OCDS Merge directly.

**Comment by jpmckinney** [comment]
Closing as #268 is closed, but can re-open whenever we have a use case for re-use.
