### ISSUE TITLE
mapping-sheet: Add option to skip check for implicitly required fields

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/ocdskit#86]
The project level schema in OC for Infrastructure doesn't permit `null` values, since it doesn't use the releases and records mechanism.

As such the mapping-sheet script marks all the fields as required, since it checks for fields which are implicitly required in the OCDS schema (i.e. where `null` is not a permitted value).

As a temporary workaround I've created an [infrastructure branch](https://github.com/open-contracting/ocdskit/tree/infrastructure) of ocdskit which only checks for the explicitly declared required fields.

**Comment by duncandewhurst** [comment]
Agreed, this was the quick fix to get the mapping template working correctly and to share with @yolile

**Comment by jpmckinney** [comment]
There's now an `--infer-required` option, that needs to be used when working with OCDS schema.
