### ISSUE TITLE
Use OCDS Kit as a Python library

### ISSUE THREAD

**Issue by romifz** [open-contracting/ocdskit#88]
Is it possible to have a library version of OCDS Kit, so it can be imported in Python code?

**Comment by jpmckinney** [comment]
You can do that :) Used for example in https://github.com/open-contracting/kingfisher-process/blob/f5b3471d4ac094c7ea61b28ab6acd491de0e6f21/ocdskingfisherprocess/transform/upgrade_1_0_to_1_1.py

Which method do you need to use as a library? Some methods still need to be extracted from CLI commands.

**Comment by romifz** [comment]
Thank you for the example James.

I'm asking for the commands we are looking to include in the initial version of OCDS Kit Web: `package_releases`, `compile`, `mapping-sheet` and `upgrade` (which is in the example).

**Comment by jpmckinney** [comment]
Sounds good. I suggest you start with `upgrade`, and I can work on #91 to make the others available.
