### ISSUE TITLE
New command: detect-format

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/ocdskit#94]
For each file/input, returns whether it is a release, record package, or release package.

**Comment by jpmckinney** [comment]
This can also return whether the input file is line-delimited JSON, a JSON array or a JSON object.

**Comment by duncandewhurst** [comment]
+1 this would be really useful and simplify our conversations with OCDS users about how to determine the structure of the JSON file they are working with

**Comment by jpmckinney** [comment]
This command would take a filename as input, rather than read from stdin, since a user typically wants to know the format of a file (not the formats of many items in a stream).
